name: Flutter Windows CI

on:
  push:
  pull_request:

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: subosito/flutter-action@v1.5.0
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '${{ secrets.FLUTTER_VERSION }}'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop
      - name: Build Artifacts
        run: flutter build windows --release
      - name: Ensure Release Directory Exists
        run: mkdir -p build/windows/runner/Release
      - name: Archive Release
        if: always()
        run: |
          if [ -d "build/windows/runner/Release" ]; then
            zip -r Macos-Dock-${{github.ref_name}}-windows.zip build/windows/runner/Release
          else
            echo "Directory build/windows/runner/Release does not exist."
          fi
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Macos-Dock-${{github.ref_name}}-windows.zip
