name: Flutter Windows CI

on:
  push:
  pull_request:

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: subosito/flutter-action@v1.5.0
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '${{ secrets.FLUTTER_VERSION }}'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop
      - name: Build Artifacts
        run: flutter build windows --release
      - name: Display Release Folder Files
        run: dir build/windows/x64/runner/Release
      - name: Setup Path Variables
        run: |
          $sourcePath = "build/windows/x64/runner/Release"
          $destinationPath = "$(Get-Location)/Macos-Dock-main-windows.zip"
          echo "SOURCE_PATH=$sourcePath" >> $GITHUB_ENV
          echo "DEST_PATH=$destinationPath" >> $GITHUB_ENV

      - name: Verify Source Directory
        run: |
          if (!(Test-Path -Path "$env:SOURCE_PATH")) {
            throw "Source directory does not exist: $env:SOURCE_PATH"
          }

      - name: Compress Files
        run: |
          Compress-Archive -Path "$env:SOURCE_PATH" -DestinationPath "$env:DEST_PATH"
        shell: pwsh

      - name: Verify Archive Creation
        run: |
          if (!(Test-Path -Path "$env:DEST_PATH")) {
            throw "Archive creation failed: $env:DEST_PATH"
          }
          echo "Archive created successfully at: $env:DEST_PATH"
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/Macos-Dock-${{github.ref_name}}-windows.zip
